# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
