import React from "react";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "../../lib/AntdRegistry";

import "../../app/globals.css";
import Providers from "@/components/Providers";
import NavBar from "../../components/NavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Point Y Day",
  description: "Generated by Ghariani Arwa & Ben Tiba Roua",
};

const RootLayout = async ({ children }: React.PropsWithChildren) => {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    redirect("/Log/login");
  }
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100vh" }}>
        <StyledComponentsRegistry>
          <Providers>
            <NavBar>{children}</NavBar>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};
export default RootLayout;
