import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import React from "react";
import StyledComponentsRegistry from "../lib/AntdRegistry";

import { NextAuthProvider } from "@/components/NextAuthProvider";
import Providers from "@/components/Providers";
import { authOptions } from "@/lib/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Point Y Day",
  description: "Generated by Ghariani Arwa & Ben Tiba Roua",
};

export default async function RootLayout({
  children,
}: React.PropsWithChildren) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className} style={{ height: "100vh" }}>
        <NextAuthProvider session={session}>
          <StyledComponentsRegistry>
            <Providers>{children}</Providers>
          </StyledComponentsRegistry>
        </NextAuthProvider>
      </body>
    </html>
  );
}
